twig:
    file_name_pattern: '*.twig'
    globals:
        brand_name: '%env(BRAND_NAME)%'
        brand_tagline: '%env(BRAND_TAGLINE)%'
        brand_initials: '%env(BRAND_INITIALS)%'

when@test:
    twig:
        strict_variables: true
